// Généré par scripts/generate-typescript.sh à partir de openapi/schema.yaml — ne pas éditer à la main.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Forme standard d'une réponse d'erreur, commune à tous les microservices. */
        ApiError: {
            /** @description Code d'erreur stable et machine-readable, ex. "NOT_FOUND". */
            code: string;
            /** @description Message lisible destiné aux logs ou à l'affichage debug. */
            message: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
        User: {
            user_id: string;
            pseudo: string;
        };
        LNChallenge: {
            lnurl: string;
            k1: string;
        };
        LNCallbackSuccessPayload: {
            status: string;
            code: string;
        };
        /** @enum {string} */
        ExchangeCodeStatus: "onboarding" | "logged_in";
        ExchangeCodePayload: {
            status: components["schemas"]["ExchangeCodeStatus"];
            session_token?: string;
            user?: components["schemas"]["User"];
        };
        /** @enum {string} */
        SubscriptionStatus: "inactive" | "active" | "expired";
        Subscription: {
            pool_address: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            status: components["schemas"]["SubscriptionStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PoolApiDataPayload: {
            backup_pool: boolean;
            pool: components["schemas"]["Pool"];
            users: {
                [key: string]: components["schemas"]["User"];
            };
            repartition: {
                [key: string]: components["schemas"]["Repartition"];
            };
            monthly_bests: components["schemas"]["PoolBestRecord"][];
            node: components["schemas"]["Node"];
        };
        PoolBestRecord: {
            month: string;
            sdiff: string;
            username: string;
            epoch: string;
        };
        Hashrates: {
            hashrate1m: string;
            hashrate5m: string;
            hashrate1hr: string;
            hashrate1d: string;
            hashrate7d: string;
        };
        Node: {
            height: number;
            subversion: string;
            peers: number;
        };
        NumberHashrate: {
            hashrate1m: number;
            hashrate5m: number;
            hashrate1hr: number;
            hashrate1d: number;
            hashrate7d: number;
        };
        Pool: {
            runtime: components["schemas"]["PoolRuntime"];
            hashrate: components["schemas"]["PoolHashrates"];
            shares: components["schemas"]["PoolShares"];
        };
        PoolHashrates: components["schemas"]["Hashrates"] & {
            hashrate15m: string;
            hashrate6hr: string;
        };
        PoolRuntime: {
            runtime: number;
            lastupdate: string;
            Users: number;
            Workers: number;
            Idle: number;
            Disconnected: number;
        };
        PoolShares: {
            diff: number;
            accepted: number;
            rejected: number;
            bestshare: number;
            SPS1m: number;
            SPS5m: number;
            SPS15m: number;
            SPS1h: number;
        };
        Repartition: {
            shares: number;
            total_vardiff: number;
            weight: number;
            percentage: number;
        };
        PoolUser: components["schemas"]["Hashrates"] & {
            lastshare: number;
            workers: number;
            shares: number;
            bestshare: number;
            bestever: number;
            authorized: number;
            worker: components["schemas"]["Worker"][];
        };
        Worker: components["schemas"]["Hashrates"] & {
            workername: string;
            lastshare: string;
            shares: number;
            bestshare: number;
            bestever: number;
        };
        Share: {
            workinfoid: number;
            clientid: number;
            diff: number;
            /** Format: float */
            sdiff: number;
            hash: string;
            result: boolean;
            errn: number;
            createdate: string;
            /** Format: float */
            ts: number;
            workername: string;
            username: string;
            address: string;
            worker: string;
            workernameAddr: string;
            ip: string;
            agent: string;
            round: string;
            file: string;
            rejectReason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
